project_id = "vawfalhuffbdpxyassyi"

[functions.simulate-smile]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.rio-feedback]
verify_jwt = false

[functions.rio-tts]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false
