project_id = "vawfalhuffbdpxyassyi"

[functions.generate-pdf-report-v3]
verify_jwt = false

[functions.simulate-smile]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.rio-feedback]
verify_jwt = false

[functions.rio-tts]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.flow-webhook]
verify_jwt = false

[functions.create-flow-order]
verify_jwt = false

[functions.dentalink-availability]
verify_jwt = false

[functions.dentalink-pricing]
verify_jwt = false
